version: '3.8'

services:
  app:
    build: .
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis 
    networks:
      - app-network 

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network
  nginx:
      image: "nginx:latest"
      ports:
        - "8080:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - app
      networks:
        - app-network
networks:
  app-network: 
    driver: bridge 